[profile.default]
src = "packages/contracts/src"
out = "packages/contracts/out"
test = "packages/contracts/test"
script = "packages/contracts/script"
libs = ["lib", "packages/contracts/lib"]
solc_version = "0.8.24"
via_ir = true
optimizer = true
optimizer_runs = 200
ffi = false
bytecode_hash = "none"
cbor_metadata = false
fs_permissions = [{ access = "read-write", path = "./" }]
gas_reports = ["MulkToken", "EnforcementController", "IdentityRegistry", "GovOracle"]

[profile.default.fuzz]
runs = 256

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = "long"
quote_style = "double"
multiline_func_header = "params_first"
